### ISSUE TITLE
Error TX Hash when flip

### ISSUE THREAD

**Issue by dongphuongman** [Bisonai/orakl-demo-flip-coin#5] opened 2024-04-23 12:03 UTC
When i flip it raise error on explorer Fail : ErrExecutionReverted - uint(0x09), detail link 
https://baobab.klaytnscope.com/tx/0x933454f8212f7098fbfebea73ee0ea58d2af569be3b91327ac210318af1559c2?tabId=inputData

**Comment by martinkersner** [comment] 2024-04-23 12:47
Hello @dongphuongman,

Thank you for your interest in Flip Coin Orakl Network demo!

The error in your transaction is caused by insufficient balance of `FlipCoin` contract.

<img width="560" alt="image" src="https://github.com/Bisonai/orakl-demo-flip-coin/assets/2312761/39275559-12aa-459f-a653-15c741a15c92">

https://github.com/Bisonai/orakl-demo-flip-coin/blob/317c33eb7e2f36cbc7d1e4f6d1d058193d476676/contracts/src/FlipCoin.sol#L92-L95

The `FlipCoin` contract requires to hold some KLAY in order to function properly. This step has not been mentioned in README.md. I will update the document accordingly.

Cheers,
Martin

**Comment by martinkersner** [comment] 2024-04-23 12:55
The updated description has been added through PR https://github.com/Bisonai/orakl-demo-flip-coin/pull/6

**Comment by dongphuongman** [comment] 2024-04-23 15:57
> The updated description has been added through PR #6

Hello @martinkersner  
Thank for your quick reply .

Regards

**Comment by martinkersner** [comment] 2024-04-24 01:37
Glad to help! I am going to close the issue. Feel free to open new one if there is any problem 🙌

**Closed as completed by martinkersner** 2024-04-24 01:37 UTC
